/* loja_producao_logico: */

CREATE TABLE CLIENTE (
    id_cliente INTEGER PRIMARY KEY,
    cpf VARCHAR UNIQUE,
    nome VARCHAR,
    endereço VARCHAR,
    telefone VARCHAR
);

CREATE TABLE VENDA (
    id_venda INTEGER PRIMARY KEY,
    FK_CLIENTE_id_cliente INTEGER,
    funcionario_vendedor INTEGER,
    funcionario_entregou INTEGER
);

CREATE TABLE FUNCIONARIO (
    id_funcionario INTEGER PRIMARY KEY,
    nome VARCHAR,
    cpf VARCHAR UNIQUE,
    telefone VARCHAR,
    email VARCHAR,
    cargo VARCHAR
);

CREATE TABLE PRODUTOS_PRODUCAO (
    id_lote INTEGER PRIMARY KEY,
    FK_PRODUCAO_id_producao INTEGER,
    FK_VENDA_id_venda INTEGER,
    data_validade DATE,
    preco INTEGER
);

CREATE TABLE PRODUTO (
    id_produto INTEGER PRIMARY KEY,
    nome VARCHAR,
    preco INTEGER,
    quantidade INTEGER
);

CREATE TABLE PRODUCAO (
    id_producao INTEGER PRIMARY KEY,
    data DATE
);

CREATE TABLE MATERIA_PRIMA (
    id_materia_prima INTEGER PRIMARY KEY,
    nome VARCHAR,
    quantidade INTEGER,
    preco_unitario INTEGER,
    unidade_medida VARCHAR
);

CREATE TABLE LISTA_FUNCIONARIOS (
    FK_FUNCIONARIO_id_funcionario INTEGER,
    FK_PRODUCAO_id_producao INTEGER
);

CREATE TABLE LISTA_MATERIA_PRIMA (
    FK_PRODUCAO_id_producao INTEGER,
    FK_MATERIA_PRIMA_id_materia_prima INTEGER
);

CREATE TABLE LISTA_PRODUTOS (
    FK_PRODUTO_id_produto INTEGER,
    FK_VENDA_id_venda INTEGER,
    quantidade INTEGER
);
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_2
    FOREIGN KEY (FK_CLIENTE_id_cliente)
    REFERENCES CLIENTE (id_cliente)
    ON DELETE RESTRICT;
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_3
    FOREIGN KEY (funcionario_vendedor, funcionario_entregou)
    REFERENCES FUNCIONARIO (id_funcionario, id_funcionario)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_PRODUCAO ADD CONSTRAINT FK_PRODUTOS_PRODUCAO_2
    FOREIGN KEY (FK_PRODUCAO_id_producao)
    REFERENCES PRODUCAO (id_producao)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_PRODUCAO ADD CONSTRAINT FK_PRODUTOS_PRODUCAO_3
    FOREIGN KEY (FK_VENDA_id_venda)
    REFERENCES VENDA (id_venda)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_FUNCIONARIOS ADD CONSTRAINT FK_LISTA_FUNCIONARIOS_1
    FOREIGN KEY (FK_FUNCIONARIO_id_funcionario)
    REFERENCES FUNCIONARIO (id_funcionario)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_FUNCIONARIOS ADD CONSTRAINT FK_LISTA_FUNCIONARIOS_2
    FOREIGN KEY (FK_PRODUCAO_id_producao)
    REFERENCES PRODUCAO (id_producao)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_MATERIA_PRIMA ADD CONSTRAINT FK_LISTA_MATERIA_PRIMA_1
    FOREIGN KEY (FK_PRODUCAO_id_producao)
    REFERENCES PRODUCAO (id_producao)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_MATERIA_PRIMA ADD CONSTRAINT FK_LISTA_MATERIA_PRIMA_2
    FOREIGN KEY (FK_MATERIA_PRIMA_id_materia_prima)
    REFERENCES MATERIA_PRIMA (id_materia_prima)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_PRODUTOS ADD CONSTRAINT FK_LISTA_PRODUTOS_1
    FOREIGN KEY (FK_PRODUTO_id_produto)
    REFERENCES PRODUTO (id_produto)
    ON DELETE RESTRICT;
 
ALTER TABLE LISTA_PRODUTOS ADD CONSTRAINT FK_LISTA_PRODUTOS_2
    FOREIGN KEY (FK_VENDA_id_venda)
    REFERENCES VENDA (id_venda)
    ON DELETE RESTRICT;